# Generated by Django 2.0.7 on 2018-07-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180725_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password1',
            field=models.CharField(max_length=50, null=True, verbose_name='password1'),
        ),
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(max_length=50, null=True, verbose_name='password2'),
        ),
    ]
