# Generated by Django 2.0.7 on 2018-07-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20180726_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='location',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
